services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: data_pipeline_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cassandra:
    image: cassandra
    container_name: cassandra_db
    ports:
      - "9042:9042" # Porto por defecto de CQL

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: mongodb_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
  